LOCAL_PATH := $(call my-dir)

# Platform
TARGET_BOARD_PLATFORM := msm8226
TARGET_BOARD_PLATFORM_GPU := qcom-adreno305

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := krait

# Kernel
BOARD_KERNEL_CMDLINE := androidboot.console=ttyHSL0 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
TARGET_KERNEL_CONFIG := msm8226_P892T50_defconfig
TARGET_KERNEL_SOURCE := kernel/zte/blade_vec4g
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x01000000 --tags_offset 0x00000100
BOARD_KERNEL_SEPARATED_DT := true
BOARD_CUSTOM_BOOTIMG_MK := device/zte/blade_vec4g/mkbootimg.mk

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := MSM8226
TARGET_NO_BOOTLOADER := true
TARGET_INIT_VENDOR_LIB := libinit_msm

# Qualcomm support
BOARD_USES_QCOM_HARDWARE := true

# Assert
TARGET_OTA_ASSERT_DEVICE := blade_vec4g,T50

# Partitions (they are fake)
BOARD_BOOTIMAGE_PARTITION_SIZE := 230686720
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 230686720
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1073741824
BOARD_USERDATAIMAGE_PARTITION_SIZE := 13725837312
BOARD_CACHEIMAGE_PARTITION_SIZE := 734003200
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 131072

# Recovery
TARGET_RECOVERY_FSTAB := device/zte/blade_vec4g/fstab.qcom

# TWRP
DEVICE_RESOLUTION := 720x1280
BOARD_HAS_NO_REAL_SDCARD := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_LARGE_FILESYSTEM := true
TW_NO_USB_STORAGE := true
TW_NO_EXFAT_FUSE := true
TW_NO_EXFAT := true
TW_EXCLUDE_SUPERSU := true
TW_EXCLUDE_MTP := true
RECOVERY_SDCARD_ON_DATA := true
